import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
var data  = [
        {
          "Picture": "http://placehold.it/32x32",
          "PartyName": "Jubilee",
          "sections": {
            "Economic": "Kenya’s vast territorial waters provide an exclusive economic zone totalling 152,400 square kilometres of ocean. There are 11,405 square kilometres oflakes providing massive wealth potential. We have embarked on a programme of not just reviving the existing Blue Economy sector but massively expanding it. The Blue Economy can contribute hugely to the economic prosperity of our country. And crucially, it can improve the lives of those Kenyans living in our coastal areas and around our lakes – some of the most under-developed and challenging parts of our country. The Indian Ocean offers a substantial opportunity to develop a fishing industry on a huge commercial scale. The tuna catch in the Indian Ocean is estimated at almost 1,000,000 tonnes. Only 30 of the 8,600 fishing vessels working off the Kenyan coast process their tuna in Kenya. By establishing a modern fishing port and developing a fish processing industry, we could create an additional 100,000jobs and increase our GDP by between US$150 million and US$200 million. Our Commitment to the Kenyan People In the next five years, we will: Enforce the InsuranceAct which makes it unlawful for any person to place insurance offshore without prior written approval of the Commissioner of Insurance. In 2015, Kenyan importers expatriated an estimated Ksh20 billion in Marine Cargo Insurance (MCI) premiums to offshore Insurers while the premiums they paid locally amounted to a meagre Ksh2.9 billion, a mere 13% of the potential. Revive the Kenya National Shipping Line and develop the maritime transport sector including shipping, shipbuilding and repair, marine engineering, marine insurance, logistical support and finance which has potential to create at least 50,000 quality jobs. Transform Bandari College into a Maritime Centre of Excellence to help develop the skills needed to grow the Blue Economy. n Build fishing ports in Shimoni, Mombasa, Kilifi and Lamu expected to create 12,000 jobs and add Ksh20 billion to GDP. n Raise fish production from 180,000 metric tonnes to 304,000 metric tonnes per year through the regulated landing of fish. n Raise Kenya’s per capita consumption of fish, through incentivisation, from the current 4.6 kg/person/year to the African average of 10 kg/person/year. We will seek to ensure that we reap the healthy benefits of a fish diet. n Enhance the role of our artisan fishermen by organising Beach Management Units (BMUs)into viable commercial entities such as cooperatives, and support these cooperatives with both capacity building and fleet modernisation. n Diversify the tourist package to include cruise, sport fishing, game safaris, marina, dolphin and whale watching and world class malls to create job opportunities and incomes.\r\n",
            "Education": "We have accorded high priority to education which receives the highest budgetary allocation. We do this because we recognise that education is at the heart of our transformation agenda. Education is the surest way of broadening opportunities for all Kenyans irrespective of background and of reducing intergenerational poverty. The productivity of our economy hinges critically on the quality of our labour force, and it is well known that the quality and level of a mother’s education influences and ensures the health of her children, and of our future. To meet our country’s needs for equity and social justice, employment creation, andregional and global competitiveness, we will build on the ongoing reforms and to continue to improve the quality and relevance of education. We will reduce inequality and leverage our knowledge and skills in the areas of science, technology and innovation to make our labour force truly competitive in the global marketplace.We must also remember that the revitalisation of our education system can also support the transmission of responsible social values and promote national cohesionand integration. Our Commitment to the Kenyan People In the next five years, we will: Work towards achieving a 100% transition from primary to secondary school byproviding free education in all public primary and public day secondary schools. No child, irrespective of background, will drop out of school because they cannotafford tuition fees. Double the funds available under the Higher Education Loans Board to provide loans and bursaries for TVET and university students. Improve the quality and quantity of the middle level workforce by aligning the curriculum with the needs of industry, revitalising Youth Polytechnics, completing the construction of the 70 TTIs already under construction and equipping and staffing Establish formal linkages between the private sector, academia and government to solve real life issues including by linking research and analysis to important national issues and by harnessing expertise in our universities to support the industrialisation agenda. The positive impact such arrangements can achieve has already been demonstrated in current schemes where two universities are producing digital learning equipment for primary schools. Establish centres of excellence and an innovation hub to tap into the talent pool of our young people. Establish a centre of excellence in the automotive sector and position the Kenya Advanced Institute of Science and Technology (KAIST) at Konza Technopolis as a world class Science and Technology Research University which will nurture a technologically advanced population. Jubilee Manifesto 2017 Jubilee Manifesto 2017\r\n",
            "Health": "We will build and maintain the momentum of the last four years to build a healthy and productive nation by providing universal health care and scalingup preventive health measures including improved nutrition and public health education and surveillance. We will aim to achieve a dramatic reduction in communicable diseases such as malaria, TB and HIV/AIDs as well as non-communicable and lifestyle diseases such as diabetes, strokes and cancer which contribute to 40% of deaths. We will work with communities, churches and schools to help our young people stay away from high-risk behaviour such as drugs and alcohol. Our Commitment to the Kenyan People In the next five years, we will: n Achieve free, quality primary healthcare for all Kenyans. Expand the “Linda Mama” programme (free maternity programme) to mission and private hospitals and provide health cover through NHIF for all expectant mothers for a period of 12 months covering the period before and after birth. Expand NHIF cover to all Kenyans above 70 years of age and provide insurance to families with children with disability. Expand benefit packages for allNHIF members to cover a broader set of services including emergency ambulance evacuation, heart surgeries and chronic diseases. Continue the drive towards universal health care. By 2022 more than 13 million Kenyans will have health insurance through NHIF. Increase the number of health facilities at the community level, including mobile health services so that you and your family have access to a fully equipped health centre within 5 miles of your home. Continue to scale up the Managed Equipment Programme and establish 10 new referral hospitals. Establish regional cold chains for drugs and vaccines to ensure safe and high quality drugs are available in the regions. n Establish at least one specialised cancer hospital in the country to reduce the financial burden and other challenges faced by patients seeking cancer treatment. Provide internet enabled communication in all hospitals to enable medical personnel to seek expert guidance and support from specialists across the country and abroad. n Make health and medical tourism a vibrant socio-economic sub-sector in Kenya.\r\n"
          }
        },
        {
          "Picture": "http://placehold.it/32x32",
          "PartyName": "Orange Democratic Movement",
          "sections": {
            "Economic": "Bring all off-budget government revenues and expenditure on-budget, and prepare a comprehensive budget – the general budget and the government-funded budget.Complete the move from one to two budgetary levels in a manner consistent with the letter and spirit of devolution. This step is key to streamlining the size of the two levels of government, improving the efficiency of government services, and empowering county governments. Discipline the budgetary process and synchronise budget and expenditure cycles by finalising the budget two months before the start of the financial year (April 30). Improve performance contracting by using independent agencies to conduct rigorous performance evaluations of government programmes on a random basis. These evaluations will help provide feedback on resource allocation, and identify those programmes delivering the right outcomes and those that are not.",
            "Education": "Transform public education facilities at all levels into institutions that offer quality, free, basic education services in accordance with Article 53 (1b) of the Constitution by identifying alternative sources of financing for the sector. Facilitate public universities to diversify their sources of income to finance university education, with a view to lowering tuition and fees paid by students directly. \r\n",
            "Health": "Ensure proper co-ordination of the sector through implementing comprehensive reforms aimed at decentralising the country’s health management system, including; decision-making power for resource allocation and service delivery to the lower levels and to facilitate greater community involvement.\r\n"
          }
        }
      ]
ReactDOM.render(<App data={data} />, document.getElementById('root'));
registerServiceWorker();
